name: email

on:
  push:
    branches:
      - main
    paths:
      - "A/**"

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2.1.3
        id: PR
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.APP_PASSWORD}}
          subject: Test github action email
          to: anatolyburtsev@yandex.ru
          from: Myself
          body: Link to PR ${{steps.PR.outputs.pr_url}}\n PR description ${{steps.PR.title}}\n PR author ${{steps.PR.login}}\n PR merged at ${{steps.PR.merged_at}}